---
title: "Alvaro Manzanas Portfolio"
---
# About Me

Let me introduce myself, my name is Álvaro Manzanas, I am a Junior Data Analysis, Scientist, Psychologist with a background in Computer Systems Administration and Virtualization. Eager to learn and improve professionally in the world of data analysis, with curiosity and interest to know the knowledge they hide. I am characterized as an analytical person with logical thinking, as well as being creative and curious, which combines well with the organization and meticulousness with which I excel.

I hope you'll take a look at what I've been working on, you might find it interesting. And if you like to connect with me, do not hesitate to do so, here I provide some buttons where you will find how to do it. 

<ul>
  <li><a href="assets/docs/Alvaro Manzanas-CV_en.pdf" target="_blank"><i class="icon regular fa-file"></i> Curriculum</a></li>
  <li><a href="https://es.linkedin.com/in/alvaromanzanas" target="_blank"><i class="icon brands fa-linkedin"></i> LinkedIn</a></li>
  <li><a href="https://github.com/almanzanas" target="_blank"><i class="icon brands fa-github"></i> GitHub</a></li>
</ul>

