project:
  type: book
  output-dir: _book
  lib-dir: _book-lib-dir

book: 
  title: "Alvaro Manzanas"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Base R"
      chapters:
        - to_book/notebooks/00_basics_ndata.qmd
        - to_book/notebooks/01_functions_scripts.qmd
        - to_book/notebooks/02_data_into_r.qmd
        - to_book/notebooks/03_data_handling.qmd
        - to_book/notebooks/99_summary.qmd
    - part: "Data Wrangling and Model"
      chapters:
        - to_book/notebooks/11_transformations_tidyverse.qmd
        - to_book/notebooks/12_ExpDatAn.qmd
        - to_book/notebooks/13_enchanced_visualizations.qmd
        - to_book/notebooks/14_modeling2deploy.qmd
  navbar:
    background: secondary
    foreground: light
    right:
      - href: portfolio.html
        text: Portfolio
      - href: index.qmd
        text: Annotations
      - href: cv.html
        text: CV
      - icon: github
        href: http://github.com/almanzanas
        aria-label: GitHub
      - icon: bi bi-envelope
        href: "mailto:almanzanas@gmx.com"
        aria-label: e-mail
      - icon: linkedin
        href: https://es.linkedin.com/in/alvaromanzanas 
        aria-label: Linkedin
    pinned: true
  sidebar:
    tools:
      - icon: github
        href: http://github.com/almanzanas
      - icon: bi bi-envelope
        href: "mailto:almanzanas@gmx.com"
      - icon: linkedin
        href: https://es.linkedin.com/in/alvaromanzanas 
        
bibliography: references.bib

format:
  html:
    tabset: true
    theme:
      light: [cosmo, style/style.scss]
      dark: [cosmo, style/dark.scss]
    toc: true

  pdf:
    documentclass: scrreprt

editor: visual



