---
title: Annotations
date: "25/09/2024"
format: html
---
# Preface {.unnumbered}

The documents in these pages are the notes, exercises and progress I have been making throughout my learning in R. They are in the same order in which I have practiced it and belong to the books:

-   Buttrey, S. E., & Whitaker, L. R. (2017). *A Data Scientist’s Guide to Acquiring, Cleaning, and Managing Data in R*. John Wiley & Sons.
-   Santos, G. R. (2023). *Data Wrangling with R: Load, Explore, Transform and Visualize Data for Modeling with Tidyverse Libraries*. Packt Publishing.

Something that I have not yet been able to add are the notes of statistics of Antonio Pardo's reference manuals. These manuals I studied them both in the career of Psychology, also now to deepen as Data Scientist. The title could be translated as: Data Analysis in Social and Health Sciences (I-III).

-   Merino, A. P. (2014). *Análisis de datos en ciencias sociales y de la salud I*.
-   Merino, A. P., & Castellanos, R. S. M. (2011). *Análisis de datos en ciencias sociales y de la salud II*.
-   Merino, A. P., & Carnicer, M. Á. R. (2013). *Análisis de datos en ciencias sociales y de la salud III*.
